### ISSUE TITLE
Problem with patch framework native -fence.cpp

### ISSUE THREAD

**Issue by WisniaPL** [JonnyXDA/android_device_vernee_apollo#1]
frameworks/native/libs/ui/mediatek/Fence.cpp:33:13: error: out-of-line definition of 'dump' does not match any declaration in 'android::Fence'
void Fence::dump(int fd) {

**Comment by JonnyVR1** [comment]
I didn't get this error, can you please explain the steps you did to get this? your comment is not very informative at all...

**Comment by WisniaPL** [comment]
I already deal with this. Anyway thanks for reply.
